split up actions into separate stages

diff --git a/.github/workflows/lambda-deploy.yml b/.github/workflows/lambda-deploy.yml
--- a/.github/workflows/lambda-deploy.yml
+++ b/.github/workflows/lambda-deploy.yml
@@ -7,9 +7,8 @@ on:
       - 'lambda/**'
 
 jobs:
-  deploy:
+  build-and-unit-test:
     runs-on: ubuntu-latest
-    
     steps:
     - uses: actions/checkout@v2
       with:
@@ -31,27 +30,43 @@ jobs:
     - name: Run unit tests
       run: npm run test:unit
 
-    - name: CDK deploy if unit tests pass
-      run: |
-        if [ $? -eq 0 ]; then
-          cdk deploy LambdaCanaryStack-Dev --require-approval never
-        else
-          echo "Unit tests failed. Skipping CDK deployment."
-        fi
-      env:
-        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        AWS_DEFAULT_REGION: us-west-2
-     
-    # run integration tests
-    - name: Integration tests
-      run: |
-        npm run test:integration
-      env:
-        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        AWS_DEFAULT_REGION: us-west-2
+  deploy-dev:
+    name: Deploy to Dev
+    needs: build-and-unit-test
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          fetch-depth: 2  # To be able to get changed files
+      - name: CDK deploy if unit tests pass
+        run: |
+          if [ $? -eq 0 ]; then
+            cdk deploy LambdaCanaryStack-Dev --require-approval never
+          else
+            echo "Unit tests failed. Skipping CDK deployment."
+          fi
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_DEFAULT_REGION: us-west-2
 
+      # run integration tests
+      - name: Integration tests
+        run: |
+          npm run test:integration
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_DEFAULT_REGION: us-west-2
+
+  deploy-prod:
+    name: Deploy to Prod
+    needs: deploy-dev
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v2
+      with:
+        fetch-depth: 2  # To be able to get changed files
     # deploy to production
     - name: Deploy to production
       run: |
